name: plant_online_store
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_native_splash: ^2.3.9
  build_runner: ^2.4.8
  flutter_gen_runner: 5.4.0
  simple_gradient_text: ^1.3.0
  flutter_svg: ^2.0.9
  pinput: ^3.0.1
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  get_storage: ^2.1.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons_bold/
    - assets/icons_Light/
    - assets/flags/
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true